# This file contains values from Cookiecutter

default_context:
  project_name: "template-python"
  project_description: "Repositorio template para criacao de projetos em Python. U"
  organization: "ingwersen-erik"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "ingwersen_erik"
  email: "erik.ingwersen@br.ey.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
